import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Navigation } from "@/components/navigations/nav";
import { Footer } from "@/components/footer";
import Chatbot from "@/components/chatbot/chatbot";
// import ChatbotWrapper from "@/components/chatbot/chatbotwrapper";
import ChatbotWrapper from "@/components/chatbot/chatbotwrapper";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Navigation />
        {children}

        <ChatbotWrapper />
        <Chatbot />
        <Footer />
      </body>
    </html>
  );
}
